modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
[[mods]] #mandatory
modId="naturalslabsmod" #mandatory
version="1.0.6" #mandatory
displayName="Natural Slabs Mod" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
authors="EndlesNights" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that adds in functional dirt, grass slabs with accompanying supports so they work in a comparable way to the full size block.
'''
